-- Bavarian — carbon, alpine white, Bavarian blue. Generated by bin/generate-theme.py.
--
-- A self-contained colourscheme: no plugin to install, no upstream palette to
-- drift out of sync with the rest of the desktop. LazyVim accepts a function
-- for `colorscheme`, so the highlights are applied directly from the same
-- tokens every other file in this theme is generated from.

local carbon = "#08090C"
local graphite = "#0E1014"
local slate = "#161920"
local machined = "#232833"
local alpine = "#E9EBEF"
local text = "#D9DDE3"
local silver = "#AEB5BE"
local aluminium = "#6C7480"
local comment = "#5B636E"
local alpina = "#0A2E6B"
local bavarian = "#2C7FD4"
local focus = "#5AA9F0"
local ambient = "#4FB8CE"
local amber = "#D89A4E"
local motorsport = "#D2544A"
local verde = "#5FA97D"
local violet = "#A67BC9"

local function bavarian_colorscheme()
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.background = "dark"
  vim.o.termguicolors = true
  vim.g.colors_name = "bavarian"

  local hl = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end

  -- Structure
  hl("Normal", { fg = text, bg = carbon })
  hl("NormalFloat", { fg = text, bg = graphite })
  hl("FloatBorder", { fg = machined, bg = graphite })
  hl("FloatTitle", { fg = alpine, bg = graphite, bold = true })
  hl("ColorColumn", { bg = graphite })
  hl("CursorLine", { bg = graphite })
  hl("CursorColumn", { bg = graphite })
  hl("SignColumn", { bg = carbon })
  hl("VertSplit", { fg = machined })
  hl("WinSeparator", { fg = machined })
  hl("LineNr", { fg = comment })
  hl("CursorLineNr", { fg = bavarian, bold = true })
  hl("Folded", { fg = aluminium, bg = graphite })
  hl("Visual", { bg = alpina })
  hl("VisualNOS", { bg = alpina })
  hl("MatchParen", { fg = focus, bold = true })
  hl("Cursor", { fg = carbon, bg = focus })
  hl("Title", { fg = alpine, bold = true })
  hl("Directory", { fg = bavarian })
  hl("NonText", { fg = machined })
  hl("Whitespace", { fg = machined })
  hl("EndOfBuffer", { fg = carbon })
  hl("Conceal", { fg = aluminium })

  -- Chrome
  hl("StatusLine", { fg = silver, bg = graphite })
  hl("StatusLineNC", { fg = aluminium, bg = graphite })
  hl("TabLine", { fg = aluminium, bg = graphite })
  hl("TabLineFill", { bg = graphite })
  hl("TabLineSel", { fg = alpine, bg = slate, bold = true })
  hl("WinBar", { fg = silver, bg = carbon })
  hl("WinBarNC", { fg = aluminium, bg = carbon })
  hl("Pmenu", { fg = silver, bg = graphite })
  hl("PmenuSel", { fg = alpine, bg = alpina, bold = true })
  hl("PmenuSbar", { bg = graphite })
  hl("PmenuThumb", { bg = machined })
  hl("Search", { fg = carbon, bg = amber })
  hl("IncSearch", { fg = carbon, bg = focus })
  hl("CurSearch", { fg = carbon, bg = focus })
  hl("QuickFixLine", { bg = alpina })

  -- Syntax. Structure is silver, meaning is blue, literals are warm.
  hl("Comment", { fg = comment, italic = true })
  hl("Constant", { fg = ambient })
  hl("String", { fg = verde })
  hl("Character", { fg = verde })
  hl("Number", { fg = amber })
  hl("Boolean", { fg = amber })
  hl("Float", { fg = amber })
  hl("Identifier", { fg = text })
  hl("Function", { fg = focus })
  hl("Statement", { fg = bavarian })
  hl("Conditional", { fg = bavarian })
  hl("Repeat", { fg = bavarian })
  hl("Label", { fg = bavarian })
  hl("Operator", { fg = silver })
  hl("Keyword", { fg = bavarian })
  hl("Exception", { fg = motorsport })
  hl("PreProc", { fg = violet })
  hl("Include", { fg = violet })
  hl("Define", { fg = violet })
  hl("Macro", { fg = violet })
  hl("Type", { fg = ambient })
  hl("StorageClass", { fg = bavarian })
  hl("Structure", { fg = ambient })
  hl("Typedef", { fg = ambient })
  hl("Special", { fg = ambient })
  hl("Delimiter", { fg = silver })
  hl("Todo", { fg = carbon, bg = amber, bold = true })
  hl("Error", { fg = motorsport })
  hl("Underlined", { fg = focus, underline = true })

  -- Diagnostics
  hl("DiagnosticError", { fg = motorsport })
  hl("DiagnosticWarn", { fg = amber })
  hl("DiagnosticInfo", { fg = bavarian })
  hl("DiagnosticHint", { fg = ambient })
  hl("DiagnosticOk", { fg = verde })
  hl("DiagnosticUnderlineError", { sp = motorsport, undercurl = true })
  hl("DiagnosticUnderlineWarn", { sp = amber, undercurl = true })
  hl("DiagnosticUnderlineInfo", { sp = bavarian, undercurl = true })
  hl("DiagnosticUnderlineHint", { sp = ambient, undercurl = true })

  -- Diffs
  hl("DiffAdd", { fg = verde, bg = "NONE" })
  hl("DiffChange", { fg = bavarian, bg = "NONE" })
  hl("DiffDelete", { fg = motorsport, bg = "NONE" })
  hl("DiffText", { fg = focus, bold = true })
  hl("Added", { fg = verde })
  hl("Changed", { fg = bavarian })
  hl("Removed", { fg = motorsport })

  -- Treesitter
  hl("@variable", { fg = text })
  hl("@variable.builtin", { fg = violet })
  hl("@variable.parameter", { fg = silver })
  hl("@property", { fg = text })
  hl("@field", { fg = text })
  hl("@constant", { fg = ambient })
  hl("@constant.builtin", { fg = violet })
  hl("@function", { fg = focus })
  hl("@function.builtin", { fg = focus })
  hl("@function.call", { fg = focus })
  hl("@method", { fg = focus })
  hl("@constructor", { fg = ambient })
  hl("@keyword", { fg = bavarian })
  hl("@keyword.return", { fg = bavarian, bold = true })
  hl("@type", { fg = ambient })
  hl("@type.builtin", { fg = ambient })
  hl("@string", { fg = verde })
  hl("@string.escape", { fg = amber })
  hl("@number", { fg = amber })
  hl("@boolean", { fg = amber })
  hl("@comment", { fg = comment, italic = true })
  hl("@punctuation.bracket", { fg = silver })
  hl("@punctuation.delimiter", { fg = silver })
  hl("@tag", { fg = bavarian })
  hl("@tag.attribute", { fg = ambient })
  hl("@tag.delimiter", { fg = aluminium })
  hl("@markup.heading", { fg = alpine, bold = true })
  hl("@markup.link", { fg = ambient, underline = true })
  hl("@markup.raw", { fg = verde })

  -- LSP
  hl("LspReferenceText", { bg = slate })
  hl("LspReferenceRead", { bg = slate })
  hl("LspReferenceWrite", { bg = slate, underline = true })
  hl("LspInlayHint", { fg = comment, bg = graphite })

  -- Common plugins
  hl("GitSignsAdd", { fg = verde })
  hl("GitSignsChange", { fg = bavarian })
  hl("GitSignsDelete", { fg = motorsport })
  hl("TelescopeBorder", { fg = machined, bg = graphite })
  hl("TelescopeNormal", { fg = text, bg = graphite })
  hl("TelescopeTitle", { fg = alpine, bold = true })
  hl("TelescopeSelection", { fg = alpine, bg = alpina })
  hl("TelescopeMatching", { fg = focus, bold = true })
  hl("NeoTreeNormal", { fg = silver, bg = graphite })
  hl("NeoTreeNormalNC", { fg = aluminium, bg = graphite })
  hl("NeoTreeDirectoryName", { fg = silver })
  hl("NeoTreeDirectoryIcon", { fg = bavarian })
  hl("NeoTreeGitModified", { fg = bavarian })
  hl("NeoTreeGitAdded", { fg = verde })
  hl("NeoTreeGitDeleted", { fg = motorsport })
  hl("WhichKeyFloat", { bg = graphite })
  hl("WhichKey", { fg = bavarian })
  hl("WhichKeyDesc", { fg = text })
  hl("WhichKeyGroup", { fg = ambient })
  hl("NotifyERRORBorder", { fg = motorsport })
  hl("NotifyWARNBorder", { fg = amber })
  hl("NotifyINFOBorder", { fg = bavarian })
  hl("IndentBlanklineChar", { fg = machined })
  hl("IblIndent", { fg = machined })
  hl("IblScope", { fg = alpina })
end

return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = bavarian_colorscheme,
    },
  },
}
